version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data

  create_db:
    build: .
    command: python3 databases.py

    env_file:
      - .env
    restart: "no"
    depends_on:
      - db

  parser:
    build: .
    env_file:
      - .env
    depends_on:
      - db

  api:
    build: app/.
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app



volumes:
  postgres_data:
